---
- name: setup database
  hosts: vps1
  become: true
  gather_facts: false
  roles:
    - deploy_django_api

# - name: set up web_app in vps1
#   hosts: vps1
#   become: true
#   gather_facts: false
#   roles:
#     - deploy_web_api_vps1